query fetch_new_release(
  $where: service_realtime_service_bool_exp!
  $limit: Int
  $offset: Int
) {
  service: service_realtime_service(
    where: $where
    limit: $limit
    offset: $offset
  ) {
    id
    title
   
    description
    availability
    category_id
    license
    average_rate: average_rate
    logo
    supplier {
      userById {
        first_name
        last_name
        email
        id
      }
    }
    medias: realtime_service_media {
      type
      id
      url
    }

    category: realtime_service_category {
      id
      name: original_language {
        to: translation_contents {
          language_type
          name
        }
      }
    }
  }
  total: service_realtime_service_aggregate(where: $where) {
    service: aggregate {
      value: count
    }
  }
}
