// @ts-nocheck
// eslint-disable
// ---------------------------------------------------
// 🚗🚦 Generated by nuxt-typed-router. Do not modify !
// ---------------------------------------------------

export type RoutePathSchema =
  | '/'
  | '/:slug(.*)*'
  | '/about'
  | '/account/cart'
  | '/account/chat'
  | '/account/chat/index-:id'
  | '/account/checkout-and-pay'
  | '/account'
  | '/account/orders/'
  | '/account/orders/self'
  | '/account/saved/'
  | '/account/saved/realtime-service'
  | '/account/saved/virtual-service'
  | '/auction'
  | '/auth/forgetPassword'
  | '/auth/redirect'
  | '/auth/rul'
  | '/auth/setUpAccount'
  | '/auth/signIn'
  | '/auth/signUp'
  | '/chats/'
  | '/delivery'
  | '/products/'
  | '/products/new-release/realtime'
  | '/products/new-release/virtual'
  | '/products/search/realtime'
  | '/products/search/virtual'
  | '/products/special-discount/realtime'
  | '/products/virtual'
  | '/products/realtime-detail-:id'
  | '/products/virtual-category-:name-:id'
  | '/products/virtual-detail-:id'
  | '/products/category-:name-:id/'
  | '/products/category-:name-:id/new-release'
  | '/products/category-:name-:id/special-discount'
  | '/products/category-:name-:id/sub-category-:sub_name-:sub_id'
  | '/register'
  | '/services/search/realtime'
  | '/services/search/virtual'
  | '/services/top-rated/realtime'
  | '/services/category-:name-:id'
  | '/services/'
  | '/services/new-release/realtime'
  | '/services/virtual'
  | '/services/realtime-detail-:id'
  | '/services/virtual-category-:name-:id'
  | '/services/virtual-detail-:id'
  | '/store-employee/account'
  | '/store-employee/chats/'
  | '/store-employee/add-product-:storeId'
  | '/store-employee/discount'
  | '/store-employee/order-page/delivery-:storeId'
  | '/store-employee/order-page/self-:storeId'
  | '/store-employee/edit-product-:productId'
  | '/store-employee'
  | '/store-employee/order-page'
  | '/store-employee/products-:storeId'
  | '/store-employee/store';

type ValidStringPath<T> = T extends `${string} ${string}` ? false : T extends '' ? false : true;

type ValidParam<T, R extends boolean = true> = T extends `${infer A}/${infer B}`
  ? A extends `${string} ${string}`
    ? false
    : A extends `?${string}`
      ? false
      : A extends `${string} ${string}`
        ? false
        : A extends ''
          ? B extends ''
            ? true
            : false
          : B extends `?${string}`
            ? false
            : B extends `#${string}`
              ? true
              : B extends ''
                ? true
                : false
  : R extends true
    ? T extends ''
      ? false
      : ValidParam<T, false>
    : T extends `?${string}`
      ? false
      : T extends `${string} ${string}`
        ? false
        : true;

type ValidEndOfPath<T> = T extends `/`
  ? true
  : T extends ''
    ? true
    : T extends `${string} ${string}`
      ? false
      : T extends `?${string}`
        ? true
        : T extends `#${string}`
          ? true
          : false;

type ValidateSlug<T> = T extends `/${string}` ? true : false;

type ValidateAbout<T> = T extends `/about${infer TAbout}`
  ? ValidEndOfPath<TAbout> extends false
    ? "End of path '/about' is invalid"
    : true
  : false;

type ValidateAccountCart<T> = T extends `/account/cart${infer TCart}`
  ? ValidEndOfPath<TCart> extends false
    ? "End of path '/account/cart' is invalid"
    : true
  : false;

type ValidateAccountChat<T> = T extends `/account/chat${infer TChat}`
  ? ValidEndOfPath<TChat> extends false
    ? "End of path '/account/chat' is invalid"
    : true
  : false;

type ValidateAccountChatIndexId<T> = T extends `/account/chat/index-${infer TId}`
  ? ValidParam<TId> extends false
    ? "Parameter {id} of path '/account/chat/index-:id' is invalid"
    : true
  : false;

type ValidateAccountCheckoutAndPay<T> =
  T extends `/account/checkout-and-pay${infer TCheckoutAndPay}`
    ? ValidEndOfPath<TCheckoutAndPay> extends false
      ? "End of path '/account/checkout-and-pay' is invalid"
      : true
    : false;

type ValidateAccount<T> = T extends `/account${infer TAccount}`
  ? ValidEndOfPath<TAccount> extends false
    ? "End of path '/account' is invalid"
    : true
  : false;

type ValidateAccountOrders<T> = T extends `/account/orders${infer TOrders}`
  ? ValidEndOfPath<TOrders> extends false
    ? "End of path '/account/orders/' is invalid"
    : true
  : false;

type ValidateAccountOrdersSelf<T> = T extends `/account/orders/self${infer TSelf}`
  ? ValidEndOfPath<TSelf> extends false
    ? "End of path '/account/orders/self' is invalid"
    : true
  : false;

type ValidateAccountSaved<T> = T extends `/account/saved${infer TSaved}`
  ? ValidEndOfPath<TSaved> extends false
    ? "End of path '/account/saved/' is invalid"
    : true
  : false;

type ValidateAccountSavedRealtimeService<T> =
  T extends `/account/saved/realtime-service${infer TRealtimeService}`
    ? ValidEndOfPath<TRealtimeService> extends false
      ? "End of path '/account/saved/realtime-service' is invalid"
      : true
    : false;

type ValidateAccountSavedVirtualService<T> =
  T extends `/account/saved/virtual-service${infer TVirtualService}`
    ? ValidEndOfPath<TVirtualService> extends false
      ? "End of path '/account/saved/virtual-service' is invalid"
      : true
    : false;

type ValidateAuction<T> = T extends `/auction${infer TAuction}`
  ? ValidEndOfPath<TAuction> extends false
    ? "End of path '/auction' is invalid"
    : true
  : false;

type ValidateAuthForgetPassword<T> = T extends `/auth/forgetPassword${infer TForgetPassword}`
  ? ValidEndOfPath<TForgetPassword> extends false
    ? "End of path '/auth/forgetPassword' is invalid"
    : true
  : false;

type ValidateAuthRedirect<T> = T extends `/auth/redirect${infer TRedirect}`
  ? ValidEndOfPath<TRedirect> extends false
    ? "End of path '/auth/redirect' is invalid"
    : true
  : false;

type ValidateAuthRul<T> = T extends `/auth/rul${infer TRul}`
  ? ValidEndOfPath<TRul> extends false
    ? "End of path '/auth/rul' is invalid"
    : true
  : false;

type ValidateAuthSetUpAccount<T> = T extends `/auth/setUpAccount${infer TSetUpAccount}`
  ? ValidEndOfPath<TSetUpAccount> extends false
    ? "End of path '/auth/setUpAccount' is invalid"
    : true
  : false;

type ValidateAuthSignIn<T> = T extends `/auth/signIn${infer TSignIn}`
  ? ValidEndOfPath<TSignIn> extends false
    ? "End of path '/auth/signIn' is invalid"
    : true
  : false;

type ValidateAuthSignUp<T> = T extends `/auth/signUp${infer TSignUp}`
  ? ValidEndOfPath<TSignUp> extends false
    ? "End of path '/auth/signUp' is invalid"
    : true
  : false;

type ValidateChats<T> = T extends `/chats${infer TChats}`
  ? ValidEndOfPath<TChats> extends false
    ? "End of path '/chats/' is invalid"
    : true
  : false;

type ValidateDelivery<T> = T extends `/delivery${infer TDelivery}`
  ? ValidEndOfPath<TDelivery> extends false
    ? "End of path '/delivery' is invalid"
    : true
  : false;

type ValidateProducts<T> = T extends `/products${infer TProducts}`
  ? ValidEndOfPath<TProducts> extends false
    ? "End of path '/products/' is invalid"
    : true
  : false;

type ValidateProductsNewReleaseRealtime<T> =
  T extends `/products/new-release/realtime${infer TRealtime}`
    ? ValidEndOfPath<TRealtime> extends false
      ? "End of path '/products/new-release/realtime' is invalid"
      : true
    : false;

type ValidateProductsNewReleaseVirtual<T> =
  T extends `/products/new-release/virtual${infer TVirtual}`
    ? ValidEndOfPath<TVirtual> extends false
      ? "End of path '/products/new-release/virtual' is invalid"
      : true
    : false;

type ValidateProductsSearchRealtime<T> = T extends `/products/search/realtime${infer TRealtime}`
  ? ValidEndOfPath<TRealtime> extends false
    ? "End of path '/products/search/realtime' is invalid"
    : true
  : false;

type ValidateProductsSearchVirtual<T> = T extends `/products/search/virtual${infer TVirtual}`
  ? ValidEndOfPath<TVirtual> extends false
    ? "End of path '/products/search/virtual' is invalid"
    : true
  : false;

type ValidateProductsSpecialDiscountRealtime<T> =
  T extends `/products/special-discount/realtime${infer TRealtime}`
    ? ValidEndOfPath<TRealtime> extends false
      ? "End of path '/products/special-discount/realtime' is invalid"
      : true
    : false;

type ValidateProductsVirtual<T> = T extends `/products/virtual${infer TVirtual}`
  ? ValidEndOfPath<TVirtual> extends false
    ? "End of path '/products/virtual' is invalid"
    : true
  : false;

type ValidateProductsRealtimeDetailId<T> = T extends `/products/realtime-detail-${infer TId}`
  ? ValidParam<TId> extends false
    ? "Parameter {id} of path '/products/realtime-detail-:id' is invalid"
    : true
  : false;

type ValidateProductsVirtualCategoryNameId<T> =
  T extends `/products/virtual-category-${infer TName}-${infer TId}`
    ? ValidStringPath<TName> extends false
      ? "Parameter {name} of path '/products/virtual-category-:name-:id' is required"
      : ValidParam<TId> extends false
        ? "Parameter {id} of path '/products/virtual-category-:name-:id' is invalid"
        : true
    : false;

type ValidateProductsVirtualDetailId<T> = T extends `/products/virtual-detail-${infer TId}`
  ? ValidParam<TId> extends false
    ? "Parameter {id} of path '/products/virtual-detail-:id' is invalid"
    : true
  : false;

type ValidateProductsCategoryNameId<T> = T extends `/products/category-${infer TName}-${infer TId}`
  ? ValidStringPath<TName> extends false
    ? "Parameter {name} of path '/products/category-:name-:id/' is required"
    : ValidParam<TId> extends false
      ? "Parameter {id} of path '/products/category-:name-:id/' is invalid"
      : true
  : false;

type ValidateProductsCategoryNameIdNewRelease<T> =
  T extends `/products/category-${infer TName}-${infer TId}/new-release`
    ? ValidStringPath<TName> extends false
      ? "Parameter {name} of path '/products/category-:name-:id/new-release' is required"
      : ValidStringPath<TId> extends false
        ? "Parameter {id} of path '/products/category-:name-:id/new-release' is required"
        : ValidEndOfPath<undefined> extends false
          ? "End of path '/products/category-:name-:id/new-release' is invalid"
          : true
    : false;

type ValidateProductsCategoryNameIdSpecialDiscount<T> =
  T extends `/products/category-${infer TName}-${infer TId}/special-discount`
    ? ValidStringPath<TName> extends false
      ? "Parameter {name} of path '/products/category-:name-:id/special-discount' is required"
      : ValidStringPath<TId> extends false
        ? "Parameter {id} of path '/products/category-:name-:id/special-discount' is required"
        : ValidEndOfPath<undefined> extends false
          ? "End of path '/products/category-:name-:id/special-discount' is invalid"
          : true
    : false;

type ValidateProductsCategoryNameIdSubCategorySubNameSubId<T> =
  T extends `/products/category-${infer TName}-${infer TId}/sub-category-${infer TSubName}-${infer TSubId}`
    ? ValidStringPath<TName> extends false
      ? "Parameter {name} of path '/products/category-:name-:id/sub-category-:sub_name-:sub_id' is required"
      : ValidStringPath<TId> extends false
        ? "Parameter {id} of path '/products/category-:name-:id/sub-category-:sub_name-:sub_id' is required"
        : ValidStringPath<TSubName> extends false
          ? "Parameter {sub_name} of path '/products/category-:name-:id/sub-category-:sub_name-:sub_id' is required"
          : ValidParam<TSubId> extends false
            ? "Parameter {sub_id} of path '/products/category-:name-:id/sub-category-:sub_name-:sub_id' is invalid"
            : true
    : false;

type ValidateRegister<T> = T extends `/register${infer TRegister}`
  ? ValidEndOfPath<TRegister> extends false
    ? "End of path '/register' is invalid"
    : true
  : false;

type ValidateServicesSearchRealtime<T> = T extends `/services/search/realtime${infer TRealtime}`
  ? ValidEndOfPath<TRealtime> extends false
    ? "End of path '/services/search/realtime' is invalid"
    : true
  : false;

type ValidateServicesSearchVirtual<T> = T extends `/services/search/virtual${infer TVirtual}`
  ? ValidEndOfPath<TVirtual> extends false
    ? "End of path '/services/search/virtual' is invalid"
    : true
  : false;

type ValidateServicesTopRatedRealtime<T> =
  T extends `/services/top-rated/realtime${infer TRealtime}`
    ? ValidEndOfPath<TRealtime> extends false
      ? "End of path '/services/top-rated/realtime' is invalid"
      : true
    : false;

type ValidateServicesCategoryNameId<T> = T extends `/services/category-${infer TName}-${infer TId}`
  ? ValidStringPath<TName> extends false
    ? "Parameter {name} of path '/services/category-:name-:id' is required"
    : ValidParam<TId> extends false
      ? "Parameter {id} of path '/services/category-:name-:id' is invalid"
      : true
  : false;

type ValidateServices<T> = T extends `/services${infer TServices}`
  ? ValidEndOfPath<TServices> extends false
    ? "End of path '/services/' is invalid"
    : true
  : false;

type ValidateServicesNewReleaseRealtime<T> =
  T extends `/services/new-release/realtime${infer TRealtime}`
    ? ValidEndOfPath<TRealtime> extends false
      ? "End of path '/services/new-release/realtime' is invalid"
      : true
    : false;

type ValidateServicesVirtual<T> = T extends `/services/virtual${infer TVirtual}`
  ? ValidEndOfPath<TVirtual> extends false
    ? "End of path '/services/virtual' is invalid"
    : true
  : false;

type ValidateServicesRealtimeDetailId<T> = T extends `/services/realtime-detail-${infer TId}`
  ? ValidParam<TId> extends false
    ? "Parameter {id} of path '/services/realtime-detail-:id' is invalid"
    : true
  : false;

type ValidateServicesVirtualCategoryNameId<T> =
  T extends `/services/virtual-category-${infer TName}-${infer TId}`
    ? ValidStringPath<TName> extends false
      ? "Parameter {name} of path '/services/virtual-category-:name-:id' is required"
      : ValidParam<TId> extends false
        ? "Parameter {id} of path '/services/virtual-category-:name-:id' is invalid"
        : true
    : false;

type ValidateServicesVirtualDetailId<T> = T extends `/services/virtual-detail-${infer TId}`
  ? ValidParam<TId> extends false
    ? "Parameter {id} of path '/services/virtual-detail-:id' is invalid"
    : true
  : false;

type ValidateStoreEmployeeAccount<T> = T extends `/store-employee/account${infer TAccount}`
  ? ValidEndOfPath<TAccount> extends false
    ? "End of path '/store-employee/account' is invalid"
    : true
  : false;

type ValidateStoreEmployeeChats<T> = T extends `/store-employee/chats${infer TChats}`
  ? ValidEndOfPath<TChats> extends false
    ? "End of path '/store-employee/chats/' is invalid"
    : true
  : false;

type ValidateStoreEmployeeAddProductStoreId<T> =
  T extends `/store-employee/add-product-${infer TStoreId}`
    ? ValidParam<TStoreId> extends false
      ? "Parameter {storeId} of path '/store-employee/add-product-:storeId' is invalid"
      : true
    : false;

type ValidateStoreEmployeeDiscount<T> = T extends `/store-employee/discount${infer TDiscount}`
  ? ValidEndOfPath<TDiscount> extends false
    ? "End of path '/store-employee/discount' is invalid"
    : true
  : false;

type ValidateStoreEmployeeOrderPageDeliveryStoreId<T> =
  T extends `/store-employee/order-page/delivery-${infer TStoreId}`
    ? ValidParam<TStoreId> extends false
      ? "Parameter {storeId} of path '/store-employee/order-page/delivery-:storeId' is invalid"
      : true
    : false;

type ValidateStoreEmployeeOrderPageSelfStoreId<T> =
  T extends `/store-employee/order-page/self-${infer TStoreId}`
    ? ValidParam<TStoreId> extends false
      ? "Parameter {storeId} of path '/store-employee/order-page/self-:storeId' is invalid"
      : true
    : false;

type ValidateStoreEmployeeEditProductProductId<T> =
  T extends `/store-employee/edit-product-${infer TProductId}`
    ? ValidParam<TProductId> extends false
      ? "Parameter {productId} of path '/store-employee/edit-product-:productId' is invalid"
      : true
    : false;

type ValidateStoreEmployee<T> = T extends `/store-employee${infer TStoreEmployee}`
  ? ValidEndOfPath<TStoreEmployee> extends false
    ? "End of path '/store-employee' is invalid"
    : true
  : false;

type ValidateStoreEmployeeOrderPage<T> = T extends `/store-employee/order-page${infer TOrderPage}`
  ? ValidEndOfPath<TOrderPage> extends false
    ? "End of path '/store-employee/order-page' is invalid"
    : true
  : false;

type ValidateStoreEmployeeProductsStoreId<T> =
  T extends `/store-employee/products-${infer TStoreId}`
    ? ValidParam<TStoreId> extends false
      ? "Parameter {storeId} of path '/store-employee/products-:storeId' is invalid"
      : true
    : false;

type ValidateStoreEmployeeStore<T> = T extends `/store-employee/store${infer TStore}`
  ? ValidEndOfPath<TStore> extends false
    ? "End of path '/store-employee/store' is invalid"
    : true
  : false;

export type ValidatePath<T extends string> = T extends string
  ? T extends '/'
    ? T
    : ValidateSlug<T> extends true
      ? T
      : ValidateAbout<T> extends true
        ? T
        : ValidateAccountCart<T> extends true
          ? T
          : ValidateAccountChat<T> extends true
            ? T
            : ValidateAccountChatIndexId<T> extends true
              ? T
              : ValidateAccountCheckoutAndPay<T> extends true
                ? T
                : ValidateAccount<T> extends true
                  ? T
                  : ValidateAccountOrders<T> extends true
                    ? T
                    : ValidateAccountOrdersSelf<T> extends true
                      ? T
                      : ValidateAccountSaved<T> extends true
                        ? T
                        : ValidateAccountSavedRealtimeService<T> extends true
                          ? T
                          : ValidateAccountSavedVirtualService<T> extends true
                            ? T
                            : ValidateAuction<T> extends true
                              ? T
                              : ValidateAuthForgetPassword<T> extends true
                                ? T
                                : ValidateAuthRedirect<T> extends true
                                  ? T
                                  : ValidateAuthRul<T> extends true
                                    ? T
                                    : ValidateAuthSetUpAccount<T> extends true
                                      ? T
                                      : ValidateAuthSignIn<T> extends true
                                        ? T
                                        : ValidateAuthSignUp<T> extends true
                                          ? T
                                          : ValidateChats<T> extends true
                                            ? T
                                            : ValidateDelivery<T> extends true
                                              ? T
                                              : ValidateProducts<T> extends true
                                                ? T
                                                : ValidateProductsNewReleaseRealtime<T> extends true
                                                  ? T
                                                  : ValidateProductsNewReleaseVirtual<T> extends true
                                                    ? T
                                                    : ValidateProductsSearchRealtime<T> extends true
                                                      ? T
                                                      : ValidateProductsSearchVirtual<T> extends true
                                                        ? T
                                                        : ValidateProductsSpecialDiscountRealtime<T> extends true
                                                          ? T
                                                          : ValidateProductsVirtual<T> extends true
                                                            ? T
                                                            : ValidateProductsRealtimeDetailId<T> extends true
                                                              ? T
                                                              : ValidateProductsVirtualCategoryNameId<T> extends true
                                                                ? T
                                                                : ValidateProductsVirtualDetailId<T> extends true
                                                                  ? T
                                                                  : ValidateProductsCategoryNameId<T> extends true
                                                                    ? T
                                                                    : ValidateProductsCategoryNameIdNewRelease<T> extends true
                                                                      ? T
                                                                      : ValidateProductsCategoryNameIdSpecialDiscount<T> extends true
                                                                        ? T
                                                                        : ValidateProductsCategoryNameIdSubCategorySubNameSubId<T> extends true
                                                                          ? T
                                                                          : ValidateRegister<T> extends true
                                                                            ? T
                                                                            : ValidateServicesSearchRealtime<T> extends true
                                                                              ? T
                                                                              : ValidateServicesSearchVirtual<T> extends true
                                                                                ? T
                                                                                : ValidateServicesTopRatedRealtime<T> extends true
                                                                                  ? T
                                                                                  : ValidateServicesCategoryNameId<T> extends true
                                                                                    ? T
                                                                                    : ValidateServices<T> extends true
                                                                                      ? T
                                                                                      : ValidateServicesNewReleaseRealtime<T> extends true
                                                                                        ? T
                                                                                        : ValidateServicesVirtual<T> extends true
                                                                                          ? T
                                                                                          : ValidateServicesRealtimeDetailId<T> extends true
                                                                                            ? T
                                                                                            : ValidateServicesVirtualCategoryNameId<T> extends true
                                                                                              ? T
                                                                                              : ValidateServicesVirtualDetailId<T> extends true
                                                                                                ? T
                                                                                                : ValidateStoreEmployeeAccount<T> extends true
                                                                                                  ? T
                                                                                                  : ValidateStoreEmployeeChats<T> extends true
                                                                                                    ? T
                                                                                                    : ValidateStoreEmployeeAddProductStoreId<T> extends true
                                                                                                      ? T
                                                                                                      : ValidateStoreEmployeeDiscount<T> extends true
                                                                                                        ? T
                                                                                                        : ValidateStoreEmployeeOrderPageDeliveryStoreId<T> extends true
                                                                                                          ? T
                                                                                                          : ValidateStoreEmployeeOrderPageSelfStoreId<T> extends true
                                                                                                            ? T
                                                                                                            : ValidateStoreEmployeeEditProductProductId<T> extends true
                                                                                                              ? T
                                                                                                              : ValidateStoreEmployee<T> extends true
                                                                                                                ? T
                                                                                                                : ValidateStoreEmployeeOrderPage<T> extends true
                                                                                                                  ? T
                                                                                                                  : ValidateStoreEmployeeProductsStoreId<T> extends true
                                                                                                                    ? T
                                                                                                                    : ValidateStoreEmployeeStore<T> extends true
                                                                                                                      ? T
                                                                                                                      : string extends T
                                                                                                                        ? T
                                                                                                                        : `Error: ${
                                                                                                                            | ValidateSlug<T>
                                                                                                                            | ValidateAbout<T>
                                                                                                                            | ValidateAccountCart<T>
                                                                                                                            | ValidateAccountChat<T>
                                                                                                                            | ValidateAccountChatIndexId<T>
                                                                                                                            | ValidateAccountCheckoutAndPay<T>
                                                                                                                            | ValidateAccount<T>
                                                                                                                            | ValidateAccountOrders<T>
                                                                                                                            | ValidateAccountOrdersSelf<T>
                                                                                                                            | ValidateAccountSaved<T>
                                                                                                                            | ValidateAccountSavedRealtimeService<T>
                                                                                                                            | ValidateAccountSavedVirtualService<T>
                                                                                                                            | ValidateAuction<T>
                                                                                                                            | ValidateAuthForgetPassword<T>
                                                                                                                            | ValidateAuthRedirect<T>
                                                                                                                            | ValidateAuthRul<T>
                                                                                                                            | ValidateAuthSetUpAccount<T>
                                                                                                                            | ValidateAuthSignIn<T>
                                                                                                                            | ValidateAuthSignUp<T>
                                                                                                                            | ValidateChats<T>
                                                                                                                            | ValidateDelivery<T>
                                                                                                                            | ValidateProducts<T>
                                                                                                                            | ValidateProductsNewReleaseRealtime<T>
                                                                                                                            | ValidateProductsNewReleaseVirtual<T>
                                                                                                                            | ValidateProductsSearchRealtime<T>
                                                                                                                            | ValidateProductsSearchVirtual<T>
                                                                                                                            | ValidateProductsSpecialDiscountRealtime<T>
                                                                                                                            | ValidateProductsVirtual<T>
                                                                                                                            | ValidateProductsRealtimeDetailId<T>
                                                                                                                            | ValidateProductsVirtualCategoryNameId<T>
                                                                                                                            | ValidateProductsVirtualDetailId<T>
                                                                                                                            | ValidateProductsCategoryNameId<T>
                                                                                                                            | ValidateProductsCategoryNameIdNewRelease<T>
                                                                                                                            | ValidateProductsCategoryNameIdSpecialDiscount<T>
                                                                                                                            | ValidateProductsCategoryNameIdSubCategorySubNameSubId<T>
                                                                                                                            | ValidateRegister<T>
                                                                                                                            | ValidateServicesSearchRealtime<T>
                                                                                                                            | ValidateServicesSearchVirtual<T>
                                                                                                                            | ValidateServicesTopRatedRealtime<T>
                                                                                                                            | ValidateServicesCategoryNameId<T>
                                                                                                                            | ValidateServices<T>
                                                                                                                            | ValidateServicesNewReleaseRealtime<T>
                                                                                                                            | ValidateServicesVirtual<T>
                                                                                                                            | ValidateServicesRealtimeDetailId<T>
                                                                                                                            | ValidateServicesVirtualCategoryNameId<T>
                                                                                                                            | ValidateServicesVirtualDetailId<T>
                                                                                                                            | ValidateStoreEmployeeAccount<T>
                                                                                                                            | ValidateStoreEmployeeChats<T>
                                                                                                                            | ValidateStoreEmployeeAddProductStoreId<T>
                                                                                                                            | ValidateStoreEmployeeDiscount<T>
                                                                                                                            | ValidateStoreEmployeeOrderPageDeliveryStoreId<T>
                                                                                                                            | ValidateStoreEmployeeOrderPageSelfStoreId<T>
                                                                                                                            | ValidateStoreEmployeeEditProductProductId<T>
                                                                                                                            | ValidateStoreEmployee<T>
                                                                                                                            | ValidateStoreEmployeeOrderPage<T>
                                                                                                                            | ValidateStoreEmployeeProductsStoreId<T>
                                                                                                                            | ValidateStoreEmployeeStore<T>}`
  : never;

// RouteNameFromPath, RouteNameFromLocalePath
export type RouteNameFromPath<T extends string> = T extends string
  ? T extends '/'
    ? 'index'
    : ValidateSlug<T> extends true
      ? 'slug'
      : ValidateAbout<T> extends true
        ? 'about'
        : ValidateAccountCart<T> extends true
          ? 'account-cart'
          : ValidateAccountChatIndexId<T> extends true
            ? 'account-chat-index-id'
            : ValidateAccountCheckoutAndPay<T> extends true
              ? 'account-checkout-and-pay'
              : ValidateAccount<T> extends true
                ? 'account'
                : ValidateAccountOrders<T> extends true
                  ? 'account-orders'
                  : ValidateAccountOrdersSelf<T> extends true
                    ? 'account-orders-self'
                    : ValidateAccountSaved<T> extends true
                      ? 'account-saved'
                      : ValidateAccountSavedRealtimeService<T> extends true
                        ? 'account-saved-realtime-service'
                        : ValidateAccountSavedVirtualService<T> extends true
                          ? 'account-saved-virtual-service'
                          : ValidateAuction<T> extends true
                            ? 'auction'
                            : ValidateAuthForgetPassword<T> extends true
                              ? 'auth-forgetPassword'
                              : ValidateAuthRedirect<T> extends true
                                ? 'auth-redirect'
                                : ValidateAuthRul<T> extends true
                                  ? 'auth-rul'
                                  : ValidateAuthSetUpAccount<T> extends true
                                    ? 'auth-setUpAccount'
                                    : ValidateAuthSignIn<T> extends true
                                      ? 'auth-signIn'
                                      : ValidateAuthSignUp<T> extends true
                                        ? 'auth-signUp'
                                        : ValidateChats<T> extends true
                                          ? 'chats'
                                          : ValidateDelivery<T> extends true
                                            ? 'delivery'
                                            : ValidateProducts<T> extends true
                                              ? 'products-index'
                                              : ValidateProductsNewReleaseRealtime<T> extends true
                                                ? 'products-index-new-release-realtime'
                                                : ValidateProductsNewReleaseVirtual<T> extends true
                                                  ? 'products-index-new-release-virtual'
                                                  : ValidateProductsSearchRealtime<T> extends true
                                                    ? 'products-index-search-realtime'
                                                    : ValidateProductsSearchVirtual<T> extends true
                                                      ? 'products-index-search-virtual'
                                                      : ValidateProductsSpecialDiscountRealtime<T> extends true
                                                        ? 'products-index-special-discount-realtime'
                                                        : ValidateProductsVirtual<T> extends true
                                                          ? 'products-index-virtual'
                                                          : ValidateProductsRealtimeDetailId<T> extends true
                                                            ? 'products-realtime-detail-id'
                                                            : ValidateProductsVirtualCategoryNameId<T> extends true
                                                              ? 'products-virtual-category-name-id'
                                                              : ValidateProductsVirtualDetailId<T> extends true
                                                                ? 'products-virtual-detail-id'
                                                                : ValidateProductsCategoryNameId<T> extends true
                                                                  ? 'products-category-name-id'
                                                                  : ValidateProductsCategoryNameIdNewRelease<T> extends true
                                                                    ? 'products-category-name-id-new-release'
                                                                    : ValidateProductsCategoryNameIdSpecialDiscount<T> extends true
                                                                      ? 'products-category-name-id-special-discount'
                                                                      : ValidateProductsCategoryNameIdSubCategorySubNameSubId<T> extends true
                                                                        ? 'products-category-name-id-sub-category-sub_name-sub_id'
                                                                        : ValidateRegister<T> extends true
                                                                          ? 'register'
                                                                          : ValidateServicesSearchRealtime<T> extends true
                                                                            ? 'services-search-realtime'
                                                                            : ValidateServicesSearchVirtual<T> extends true
                                                                              ? 'services-search-virtual'
                                                                              : ValidateServicesTopRatedRealtime<T> extends true
                                                                                ? 'services-top-rated-realtime'
                                                                                : ValidateServicesCategoryNameId<T> extends true
                                                                                  ? 'services-category-name-id'
                                                                                  : ValidateServices<T> extends true
                                                                                    ? 'services-index'
                                                                                    : ValidateServicesNewReleaseRealtime<T> extends true
                                                                                      ? 'services-new-release-realtime'
                                                                                      : ValidateServicesVirtual<T> extends true
                                                                                        ? 'services-index-virtual'
                                                                                        : ValidateServicesRealtimeDetailId<T> extends true
                                                                                          ? 'services-realtime-detail-id'
                                                                                          : ValidateServicesVirtualCategoryNameId<T> extends true
                                                                                            ? 'services-virtual-category-name-id'
                                                                                            : ValidateServicesVirtualDetailId<T> extends true
                                                                                              ? 'services-virtual-detail-id'
                                                                                              : ValidateStoreEmployeeAccount<T> extends true
                                                                                                ? 'store-employee-account'
                                                                                                : ValidateStoreEmployeeChats<T> extends true
                                                                                                  ? 'store-employee-chats'
                                                                                                  : ValidateStoreEmployeeAddProductStoreId<T> extends true
                                                                                                    ? 'store-employee-add-product-storeId'
                                                                                                    : ValidateStoreEmployeeDiscount<T> extends true
                                                                                                      ? 'store-employee-discount'
                                                                                                      : ValidateStoreEmployeeOrderPageDeliveryStoreId<T> extends true
                                                                                                        ? 'store-employee-order-page-index-delivery-storeId'
                                                                                                        : ValidateStoreEmployeeOrderPageSelfStoreId<T> extends true
                                                                                                          ? 'store-employee-order-page-index-self-storeId'
                                                                                                          : ValidateStoreEmployeeEditProductProductId<T> extends true
                                                                                                            ? 'store-employee-edit-product-productId'
                                                                                                            : ValidateStoreEmployee<T> extends true
                                                                                                              ? 'store-employee'
                                                                                                              : ValidateStoreEmployeeProductsStoreId<T> extends true
                                                                                                                ? 'store-employee-products-storeId'
                                                                                                                : ValidateStoreEmployeeStore<T> extends true
                                                                                                                  ? 'store-employee-store'
                                                                                                                  : never
  : never;

export type TypedPathParameter<T extends string> = ValidatePath<T> | RoutePathSchema;
