// @ts-nocheck
// eslint-disable
// ---------------------------------------------------
// 🚗🚦 Generated by nuxt-typed-router. Do not modify !
// ---------------------------------------------------

export type {
  TypedLocationAsRelativeRaw,
  TypedResolvedMatcherLocation,
  TypedRoute,
  TypedRouteFromName,
  TypedRouteLocation,
  TypedRouteLocationFromName,
  TypedRouteLocationRaw,
  TypedRouteLocationRawFromName,
  TypedRouter,
  NuxtRoute,
} from './__router';
export { routesNames } from './__routes';
export type {
  RoutesNamedLocations,
  RoutesNamedLocationsResolved,
  RoutesNamesList,
  RoutesNamesListRecord,
  RoutesParamsRecord,
} from './__routes';
export { useRoute } from './__useTypedRoute';
export { useRouter } from './__useTypedRouter';
export { useLink } from './__useTypedLink';
export { navigateTo } from './__navigateTo';
export { definePageMeta } from './__definePageMeta';
export { helpers } from './__helpers';

export type {
  ValidatePath,
  RoutePathSchema,
  TypedPathParameter,
  RouteNameFromPath,
} from './__paths';
export { useLocalePath, useLocaleRoute } from './__i18n-router';
export type { TypedToLocalePath, TypedLocaleRoute, I18nLocales } from './__i18n-router';
