query fetch_subcity {
  sub_city {
    id
    longitude
    latitude
    city_region_id
    name: original_language {
      to: translation_contents {
        name
        type: language_type
      }
    }
  }
}
