query {
  cities: region_city {
    id
    original_language {
      translation_contents {
        language_type
        name
      }
    }
    sub_cities {
      id
      original_language {
        translation_contents {
          language_type
          name
        }
      }
    }
  }
}
