query shippingAddress($customerId: String!) {
  address:shipping_address(where: {customer_id:{_eq: $customerId}}) {
    id
    email
    phone_number1
    phone_number2
    description
    state_provinence
    longitude
    latitude
    sub_city{
      name:original_language{
        to:translation_contents{
          name
          language_type
        }
      }
      region:region_city{
        name:original_language{
          to:translation_contents{
            name
            language_type
          }
        }
      }
    }
    zip_code
  }
}
